### ISSUE TITLE
The version of protobuf in use does not match the version of protobuf in use in Apache arrow

### ISSUE THREAD

**Issue by dbaxa** [apache/orc#1425] opened 2023-03-01 01:29 UTC
The version of protobuf in [use - 3.5.1] (https://github.com/apache/orc/blob/d403e11b7eab126259fb0683c0eb5c6131fd347b/cmake_modules/ThirdpartyToolchain.cmake#L17)  does not match the version of protobuf in use in Apache arrow - [21.3](https://github.com/apache/arrow/blob/45918a90a6ca1cf3fd67c256a7d6a240249e555a/cpp/thirdparty/versions.txt#L92) this can cause incompatibility issues such as when pyarrow is used at the same time as pyorc[0][1].

[0] https://github.com/noirello/pyorc/issues/10

[1]

```[libprotobuf FATAL /Users/ec2-user/pyorc/deps/orc-1.8.1/build/protobuf_ep-prefix/src/protobuf_ep/src/google/protobuf/message_lite.cc:71] CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of orc.proto.RowIndex.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/ec2-user/code/example-repo/example-thing/bin/cli.py", line 55, in <module>
    cli_group(prog_name="pipenv run sc")
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ec2-user/code/example-repo/example-thing/commands/cards.py", line 178, in save
    output.save_as_orc(filename)
  File "/Users/ec2-user/code/example-repo/example-thing/core/classes/output.py", line 246, in save_as_orc
    with pyorc.Writer(
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/pyorc-0.9.0-py3.11-macosx-13-arm64.egg/pyorc/writer.py", line 86, in __exit__
  File "/Users/ec2-user/.local/share/virtualenvs/example-repo-aG8AhNTx/lib/python3.11/site-packages/pyorc-0.9.0-py3.11-macosx-13-arm64.egg/pyorc/writer.py", line 91, in close
RuntimeError: CHECK failed: (bytes_produced_by_serialization) == (byte_size_before_serialization): Byte size calculation and serialization were inconsistent.  This may indicate a bug in protocol buffers or it may be caused by concurrent modification of orc.proto.RowIndex.
Python(9491,0x1ecba8140) malloc: *** error for object 0x600002c1c188: pointer being freed was not allocated
Python(9491,0x1ecba8140) malloc: *** set a breakpoint in malloc_error_break to debug
Process 9491 stopped
* thread #2, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001915e6868 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1915e6868 <+8>:  b.lo   0x1915e6888               ; <+40>
    0x1915e686c <+12>: pacibsp 
    0x1915e6870 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1915e6874 <+20>: mov    x29, sp
Target 0: (Python) stopped.
```

**Comment by dongjoon-hyun** [comment] 2023-03-01 01:52
Thank you for reporting, @dbaxa .

cc @wgtmac , @stiga-huang , @coderex2522

**Comment by dongjoon-hyun** [comment] 2023-03-01 01:55
FYI, @dbaxa . Apache ORC community supports PyArrow and Dask in Python languages only, not `PyORC`. It just a personal 3rd party repository.
- https://orc.apache.org/docs/pyarrow.html
- https://orc.apache.org/docs/dask.html

**Comment by dbaxa** [comment] 2023-03-01 02:09
Hi @dongjoon-hyun in this specific case the issue is about the version of protobuf not matching what it should between apache projects. (As an aside - I will attempt to use the pyarrow library again but it seems to have various issues vs the `pyorc` library).

**Comment by wgtmac** [comment] 2023-03-01 02:11
I am not sure if this is already addressed by the Apache Arrow community. https://github.com/apache/arrow/issues/34191

**Comment by dongjoon-hyun** [comment] 2023-03-01 02:45
Of course, I understand what is the issue, @dbaxa . What I mentioned that PyORC is not valid at all as a reproducible example for bug reporting. :)

**Comment by dongjoon-hyun** [comment] 2023-12-24 22:55
Since `Apache Arrow 12.0.0+` has been containing the fix, let me close this. Thank you for reporting.

- https://arrow.apache.org/release/12.0.0.html (2 May 2023)
  - [GH-34191](https://github.com/apache/arrow/issues/34191) - [C++] Ensure using the same ProtoBuf in bundled ORC
  - https://github.com/apache/arrow/commit/7db7e6ac846199678e2694f173df6dd6376ee823

**Closed by dongjoon-hyun** 2023-12-24 22:55 UTC
