### ISSUE TITLE
Tests failure on 1.7.3

### ISSUE THREAD

**Issue by ArchangeGabriel** [apache/orc#1068] opened 2022-03-18 14:27 UTC
While building for Arch Linux, I’ve encountered some tests failures (after backporting ffbd34115322cf3e0eb6963002c540ea449362d2):
```
[ RUN      ] TestPredicateLeaf.testIntNullSafeEqualsBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:635: Failure
      Expected: TruthValue::YES_NO
      Which is: 4-byte object <05-00 00-00>
To be equal to: evaluate(pred, createIntStats(10, 100), &bf)
      Which is: 4-byte object <01-00 00-00>
[  FAILED  ] TestPredicateLeaf.testIntNullSafeEqualsBloomFilter (1 ms)
[ RUN      ] TestPredicateLeaf.testIntEqualsBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:652: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createIntStats(10, 100, true), &bf)
      Which is: 4-byte object <04-00 00-00>
[  FAILED  ] TestPredicateLeaf.testIntEqualsBloomFilter (0 ms)
[ RUN      ] TestPredicateLeaf.testIntInBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:667: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createIntStats(10, 100, true), &bf)
      Which is: 4-byte object <04-00 00-00>
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:670: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createIntStats(10, 100, true), &bf)
      Which is: 4-byte object <04-00 00-00>
[  FAILED  ] TestPredicateLeaf.testIntInBloomFilter (0 ms)
```
```
[ RUN      ] TestPredicateLeaf.testDateNullSafeEqualsBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:778: Failure
      Expected: TruthValue::YES_NO
      Which is: 4-byte object <05-00 00-00>
To be equal to: evaluate(pred, createDateStats(10.0, 100.0), &bf)
      Which is: 4-byte object <01-00 00-00>
[  FAILED  ] TestPredicateLeaf.testDateNullSafeEqualsBloomFilter (0 ms)
[ RUN      ] TestPredicateLeaf.testDateEqualsBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:795: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createDateStats(10.0, 100.0, true), &bf)
      Which is: 4-byte object <04-00 00-00>
[  FAILED  ] TestPredicateLeaf.testDateEqualsBloomFilter (0 ms)
[ RUN      ] TestPredicateLeaf.testDateInBloomFilter
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:812: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createDateStats(10.0, 100.0, true), &bf)
      Which is: 4-byte object <04-00 00-00>
/build/apache-orc/src/orc-1.7.3/c++/test/TestPredicateLeaf.cc:815: Failure
      Expected: TruthValue::YES_NO_NULL
      Which is: 4-byte object <06-00 00-00>
To be equal to: evaluate(pred, createDateStats(10.0, 100.0, true), &bf)
      Which is: 4-byte object <04-00 00-00>
[  FAILED  ] TestPredicateLeaf.testDateInBloomFilter (0 ms)
```
```
[ RUN      ] TestBloomFilter.testBloomFilterBasicOperations
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:134: Failure
Value of: bloomFilter.mBitSet->get(288)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:134: Failure
Value of: bloomFilter.mBitSet->get(246)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:134: Failure
Value of: bloomFilter.mBitSet->get(306)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:134: Failure
Value of: bloomFilter.mBitSet->get(228)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:138: Failure
Value of: bloomFilter.mBitSet->get(458)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:138: Failure
Value of: bloomFilter.mBitSet->get(545)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:138: Failure
Value of: bloomFilter.mBitSet->get(717)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:140: Failure
Value of: bloomFilter.mBitSet->get(526)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:140: Failure
Value of: bloomFilter.mBitSet->get(40)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:140: Failure
Value of: bloomFilter.mBitSet->get(480)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:140: Failure
Value of: bloomFilter.mBitSet->get(86)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:144: Failure
Value of: bloomFilter.mBitSet->get(308)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:144: Failure
Value of: bloomFilter.mBitSet->get(335)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:144: Failure
Value of: bloomFilter.mBitSet->get(108)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:144: Failure
Value of: bloomFilter.mBitSet->get(535)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:148: Failure
Value of: bloomFilter.mBitSet->get(279)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:148: Failure
Value of: bloomFilter.mBitSet->get(15)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:148: Failure
Value of: bloomFilter.mBitSet->get(54)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:150: Failure
Value of: bloomFilter.mBitSet->get(680)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:150: Failure
Value of: bloomFilter.mBitSet->get(818)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:150: Failure
Value of: bloomFilter.mBitSet->get(434)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:150: Failure
Value of: bloomFilter.mBitSet->get(232)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:154: Failure
Value of: bloomFilter.testLong(111)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:157: Failure
Value of: bloomFilter.testLong(-1)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:159: Failure
Value of: bloomFilter.testLong(-111)
  Actual: false
Expected: true
[  FAILED  ] TestBloomFilter.testBloomFilterBasicOperations (0 ms)
[ RUN      ] TestBloomFilter.testBloomFilterSerialization
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:262: Failure
Value of: dstBloomFilter->testLong(11)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:263: Failure
Value of: dstBloomFilter->testLong(111)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:267: Failure
Value of: dstBloomFilter->testLong(-11)
  Actual: false
Expected: true
/build/apache-orc/src/orc-1.7.3/c++/test/TestBloomFilter.cc:268: Failure
Value of: dstBloomFilter->testLong(-111)
  Actual: false
Expected: true
[  FAILED  ] TestBloomFilter.testBloomFilterSerialization (0 ms)
```
And in the second suite:
```
[ RUN      ] TestFileScan.testErrorHandling
/build/apache-orc/src/orc-1.7.3/tools/test/TestFileScan.cc:209: Failure
Expected: (std::string::npos) != (error.find(error_msg)), actual: 18446744073709551615 vs 18446744073709551615
[  FAILED  ] TestFileScan.testErrorHandling (27 ms)
```

We build with those CMake flags:
```
    -DCMAKE_CXX_FLAGS="${CXXFLAGS} -fPIC -ffat-lto-objects" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="/usr" \
    -DLZ4_HOME="/usr" \
    -DPROTOBUF_HOME="/usr" \
    -DSNAPPY_HOME="/usr" \
    -DZLIB_HOME="/usr" \
    -DZSTD_HOME="/usr" \
    -DORC_PREFER_STATIC_ZLIB=OFF \
    -DBUILD_LIBHDFSPP=OFF \
    -DBUILD_JAVA=OFF \
    -DINSTALL_VENDORED_LIBS=OFF
```

Please tell me what I can provide you with to assist in the resolution of these failures.

**Comment by ArchangeGabriel** [comment] 2022-03-28 20:26
Sorry if there has been a misunderstanding about how #1065 in involved here, I meant that we backport this patch on top of current release else tests fails, but [we already patched for that since 1.6.7](https://github.com/archlinux/svntogit-community/commit/a6c762ea2e176b5a8585a591ab299bc420027a53#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422R23).

The error is unrelated and new, it did not occur in 1.7.1. I’m not sure I have tried rebuilding 1.7.1 recently though, I should check whether it does still build fine or if the regression comes from a dependency change.

**Comment by dongjoon-hyun** [comment] 2022-03-28 20:31
No problem. We are looking forward to seeing your test result. Let me know when you have a new result.

**Comment by ArchangeGabriel** [comment] 2022-03-28 20:40
Same failures on 1.7.1 (+TestDecompression.testLzoLong that was fixed since). So there has been a dependency related change. Since they are not a lot of dependencies involved (I don’t know for this particular tests, but you might be able to tell me), given what changed on our side in this lapse of time, it seems it could be either protobuf (that went from 3.17.3 to 3.19.4) or gcc (11.1 to 11.2). Unfortunately trying older version of those is quite involved, so I’ll not be able to pinpoint any of those if they are the culprit.

**Comment by dongjoon-hyun** [comment] 2022-03-28 21:57
According to the context, the root cause is unclear to me either.

> The error is unrelated and new, it did not occur in 1.7.1.

> Same failures on 1.7.1 

Back to the basic, it's hard to consider something as a bug if we cannot reproduce it. In addition, we don't know what you have in your fork or what you have in your Arch Linux build and test system yet. We have four releases like the following. Could you confirm that which tag is the last working tag for you?

- https://github.com/apache/orc/releases/tag/v1.7.0
- https://github.com/apache/orc/releases/tag/v1.7.1
- https://github.com/apache/orc/releases/tag/v1.7.2
- https://github.com/apache/orc/releases/tag/v1.7.3

**Comment by dongjoon-hyun** [comment] 2022-03-30 02:41
Thank you for the details, @ArchangeGabriel . Given the analysis, I'm closing this issue `Tests failure on 1.7.3`.
As you mentioned here, we had better restart with a new narrow-downed specific GitHub issue for the specific failure later.

**Closed by dongjoon-hyun** 2022-03-30 02:41 UTC
